#! /usr/bin/perl -w

	#=================
	# REMOVE ZOMBIES
	#=================
$usr=`whoami`;
chomp($usr);
@removelist=("avgisar","avggps","Z_prp","avgprp","kermit","expect","perl");
foreach $xx (@removelist){
	$cmd="ps -u $usr -o pid,command | grep \"$xx\"";
	#print"test 1 cmd = $cmd\n";
	@pslist = `$cmd`;
	#$ii=0; foreach(@pslist){chomp($_); print"test 0 $ii, $pslist[$ii]\n"; $ii++}
	foreach $pscmd (@pslist){
		chomp($pscmd);
		#print"test 2 $pscmd\n";
		if( $pscmd =~ /grep/){
			#print"test 3 $pscmd\n";
		} else {
			#print"test 4 $pscmd\n";
			$pscmd =~ s/^[\s\t]+//;
			$pscmd =~ s/\s+$//;
			@d=split/[ ]+/,$pscmd;
			#$i=0;foreach $str (@d){print"$i : $str\n"; $i++}
			$cmd="kill -9 $d[0]";
			#print"cmd = $cmd\n";
			`$cmd`;
		}
	}
}
exit;

