#!/usr/bin/perl -X
#   ./LastAvg rad_avg (or 'gps_avg', 'wxt_raw', etc)

use lib $ENV{MYLIB};
use perltools::MRtime;
use perltools::MRutilities;

my $a = shift();

my $s = `LastDataRecord $a`;
chomp $s;
$str =~ s/^\s+//;  # remove leading blanks

my $recno;  
my $dt;

my @w = split/[, ]+/,$s;
#$i=0; foreach(@w){printf" $i  $w[$i] %d\n",isnumber($w[$i]); $i++}

if ( $#w<7 || !(isnumber($w[0]) && 
isnumber($w[1]) && isnumber($w[2]) && 
isnumber($w[3]) && isnumber($w[4]) && 
isnumber($w[5])) ){
	$recno=0;
	$dt=0;
	print"0   0\n";
}elsif ($w[0] =~ /^20/){
	$recno=0;
	$dt=datesec($w[0],$w[1],$w[2],$w[3],$w[4],$w[5]);
	print"$recno   $dt  $w[0] $w[1] $w[2] $w[3] $w[4] $w[5]\n";
} else {
	$recno=$w[0];
	$dt=datesec($w[1],$w[2],$w[3],$w[4],$w[5],$w[6]);
	print"$recno   $dt  $w[1] $w[2] $w[3] $w[4] $w[5] $w[6]\n";
}

exit 0;
