#!/usr/bin/perl -w

my @x = `ls -d $ENV{DAQFOLDER}/data/data* 2>/dev/null`;
if ($#x <0){print"0"; exit 1}

my $s;
chomp($s=$x[$#x]);

if($#ARGV<0){print"$s";}
else {
	my $a = shift();
	my @rw = `ls -1 $s/$a*.txt 2>/dev/null`;
	#foreach(@rw){chomp($_); print"$_\n"}
	if ($#rw < 0 ){exit 1}
	else {
		chomp($fz=$rw[$#rw]); 
		$fz =~ s/^\s+//;
		print"$fz";
	}
}
exit 0;
