#!/usr/bin/perl -w
# call
#	LastDataFolder -- if a data folder exists
#		/Users/rmr/swmain/apps/PRP/data/data_20150804T005357Z
#	LastDataFolder -- if a data folder does NOT exist
#		0
#	LastDataFolder prp_raw -- if a data folder and time series folder exists
#		/Users/rmr/swmain/apps/PRP/data/data_20150804T005357Z/prp_raw_20150804.txt
#	LastDataFolder prp_raw -- if a data folder or time series folder do NOT exist
#		0
my (@x);

if($#ARGV<0){
	@x = `find $ENV{DAQDATAFOLDER} -name data_* -print`;
} else {
	$dat = $ARGV[0];
	@x = `find $ENV{DAQDATAFOLDER} -name *$dat* -print`;
}
if( $#x < 0 ){print"0";exit 1}
print $x[$#x];
exit 0;
