#!/bin/bash

# crontab -e to set this cron job
#To use my bashrc stuff
#MAILTO=""
#BASH_ENV="$HomePath/.bashrc"
#SHELL=/bin/bash
#    SBD transmit
#26,56 * * * * $DAQSWFOLDER/sbd_transmit >> $DAQDATAFOLDER/sbdlog
#    Check and reboot
#14 * * * * $DAQSWFOLDER/UpdateDaq >> $DAQDATAFOLDER/daqlog
			
#v1 150629
#v2 160211
version="v11 160212"
#export DAQFOLDER="$HomePath/swmain/apps/ISAR3"
#export DAQSWFOLDER=$DAQFOLDER"/sw"
#export DAQLIB=$DAQFOLDER"/tools"
#export MYLIB=$DAQLIB
#export DAQDATAFOLDER=$DAQFOLDER"/data"
#export SETUPFILE=$DAQFOLDER"/sw/setup/su.txt"
#echo $PATH | grep -q -s $DAQSWFOLDER
#if [ $? -eq 1 ] ; then
#    PATH=$PATH\:$DAQSWFOLDER\:.
#    export PATH
#fi

cd $DAQSWFOLDER

echo $version" ====================" >> $DAQDATAFOLDER/daqlog;
date -u "+%Y %m %d %H %M %S Z" >> $DAQDATAFOLDER/daqlog;

DaqUpdate >> $DAQDATAFOLDER/daqlog

chk=`cat /tmp/tmpdaq`;
if [ $chk -eq 1 ] > /dev/null ; then
#	echo UpdateDaq no reboot
	echo "UpdateDaq, no reboot." >> $DAQDATAFOLDER/daqlog
	exit 0;
fi

if [ $chk -eq 0 ] > /dev/null ; then
	echo REBOOT
	echo "REBOOT." >> $DAQDATAFOLDER/daqlog
		# STOPISAR
 	$DAQSWFOLDER/KillScreen >> $DAQDATAFOLDER/daqlog
 	$DAQSWFOLDER/Cleanupisar >> $DAQDATAFOLDER/daqlog
		# STARTISAR
	$DAQSWFOLDER/PrepareForRun >> $DAQDATAFOLDER/daqlog
	screen -S ISAR -d -m -c $DAQSWFOLDER/tools/screenrc_isar.txt
		# START PROCESSES
	screen -S ISAR -p 1 -X stuff "bash$(printf \\r)"
	screen -S ISAR -p 1 -X stuff "G$(printf \\r)"

	#echo UpdateDaq, reboot exit >> $DAQDATAFOLDER/daqlog
	exit 1;
fi
exit 0;

